<!DOCTYPE html>
<title>Canvas test: 2d.imageData.put.null</title>
<script src="../tests.js"></script>
<link rel="stylesheet" href="../tests.css">
<link rel="prev" href="2d.imageData.object.round.html" title="2d.imageData.object.round">
<link rel="next" href="2d.imageData.put.nonfinite.html" title="2d.imageData.put.nonfinite">
<body class="show_output">
<p>
 <a href="2d.imageData.object.round.html" accesskey="p" title="[p] 2d.imageData.object.round">&lt;</a>
 <a href="index.html">[index]</a>
 <a href="2d.imageData.put.nonfinite.html" accesskey="n" title="[n] 2d.imageData.put.nonfinite">&gt;</a>
<h1><a href="index.2d.html">2d</a>.<a href="index.2d.imageData.html">imageData</a>.<a href="index.2d.imageData.put.html">put</a>.null</h1>
<p class="desc">putImageData() with null imagedata throws TYPE_MISMATCH_ERR</p>
<div class="refs">References:
<ul>
<li><a href="spec.html#testrefs.2d.imageData.put.null">2d.imageData.put.null</a>
<li><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=421715">Bugzilla</a>
</ul>
</div>

<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
_addTest(function(canvas, ctx) {

try { var _thrown = false;
  ctx.putImageData(null, 0, 0);
} catch (e) { if (e.code != DOMException.TYPE_MISMATCH_ERR) _fail("Failed assertion: expected exception of type TYPE_MISMATCH_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type TYPE_MISMATCH_ERR: ctx.putImageData(null, 0, 0)"); }


});
</script>

